// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE1c7P1IjMXIPs9htgqt9eBDXVLHIrFk4',
    appId: '1:913696249326:web:5c3a6ed2f945780e50aaff',
    messagingSenderId: '913696249326',
    projectId: 'banquetbookzvendor',
    authDomain: 'banquetbookzvendor.firebaseapp.com',
    storageBucket: 'banquetbookzvendor.appspot.com',
    measurementId: 'G-5PQG8J8KZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3g3wT51ehC8eKPx6B8k5vbEOyvSJbeL4',
    appId: '1:913696249326:android:c9d739da6138fa5850aaff',
    messagingSenderId: '913696249326',
    projectId: 'banquetbookzvendor',
    storageBucket: 'banquetbookzvendor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0FyqRvoMbEO9VvGMbeljLf9KwgD5NuSY',
    appId: '1:913696249326:ios:516f19e51c1624d750aaff',
    messagingSenderId: '913696249326',
    projectId: 'banquetbookzvendor',
    storageBucket: 'banquetbookzvendor.appspot.com',
    iosBundleId: 'com.example.assignmet1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0FyqRvoMbEO9VvGMbeljLf9KwgD5NuSY',
    appId: '1:913696249326:ios:516f19e51c1624d750aaff',
    messagingSenderId: '913696249326',
    projectId: 'banquetbookzvendor',
    storageBucket: 'banquetbookzvendor.appspot.com',
    iosBundleId: 'com.example.assignmet1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE1c7P1IjMXIPs9htgqt9eBDXVLHIrFk4',
    appId: '1:913696249326:web:5bb9fea51881ec9650aaff',
    messagingSenderId: '913696249326',
    projectId: 'banquetbookzvendor',
    authDomain: 'banquetbookzvendor.firebaseapp.com',
    storageBucket: 'banquetbookzvendor.appspot.com',
    measurementId: 'G-26WNVTW501',
  );
}
